---
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Full Publication List 

On [Google Scholar](https://scholar.google.com/citations?user=-TbbZWQAAAAJ&hl=en).

## Dissertation

**Papendieck, A.** (2019). More-than-social innovation: The material and discursive enactment of an open ed-tech network (Thesis). http://dx.doi.org/10.26153/tsw/2703


Committee: [Joan Hughes (chair)](https://education.utexas.edu/faculty/joan_hughes), [Flavio Azevedo](https://education.utexas.edu/faculty/flavio_azevedo), [Paul Resta](https://education.utexas.edu/faculty/paul_resta), [Clay Spinuzzi](https://liberalarts.utexas.edu/rhetoric/faculty/spinuzzi)

## Selected Publications

The publications below represent my most recent work on learning and technology innovation.  For prior technical and scientific publications, see my [**Full CV**](https://utexas.app.box.com/v/Papendieck-CV) or [Google Scholar Profile](https://scholar.google.com/citations?user=-TbbZWQAAAAJ&hl=en). 

### Peer Reviewed Journal Articles

**Papendieck, A.**, & Hughes, J. E. (forthcoming). Critical Innovators: How Teachers and Entrepreneurs Position Themselves as Technology Innovators in Schools. Contemporary Issues in Technology and Teacher Education (CITE) - General.

Nguyen, K. A., Azevedo, F. S., & **Papendieck, A.** (2021). No longer an imaginary case: Community, plans, and actions in canoeing rapids. Journal of the Learning Sciences, 30(4–5), 529–575. https://doi.org/10.1080/10508406.2021.1936530

**Papendieck, A.** (2018). Technology for Equity and Social Justice in Education: A Critical Issue Overview. Texas Education Review, 6(1), 1–9. https://doi.org/10.15781/t2891278v

### Peer Reviewed Conference Proceedings and Presentations

**Papendieck, A.**, Hasty, B., Knowles, J. (accepted). Partnering for Change: Types and Characteristics of School-Community Arts Partnerships. American Education Research Association (AERA) Conference 2022, San Diego, CA.

**Papendieck, A.** (2021). Productive Syncretic Engagement for Knowledgeable Network Performance. American Education Research Association (AERA) Conference 2021, SIG Learning Sciences. 

**Papendieck, A.**, Hasty, B., Knowles, J. (2021). Learning in an Arts Education Collective Impact Initiative. 15th International Conference of the International Society of the Learning Sciences (ISLS) 2021.

Nguyen, K., Azevedo, F., & **Papendieck, A.** (2020). On Planning the Canoeing of Rapids and Its Reasoning Processes. In Gresalfi, M. and Horn, I. S. (Eds.), The Interdisciplinarity of the Learning Sciences, 14th International Conference of the Learning Sciences (ICLS) 2020, Volume 1 (pp. 215-222). Nashville, Tennessee: International Society of the Learning Sciences. https://repository.isls.org//handle/1/6505

**Papendieck, A.** (2020). A Computational Approach to Modeling Online Identity Discourses. In Gresalfi, M. and Horn, I. S. (Eds.), The Interdisciplinarity of the Learning Sciences, 14th International Conference of the Learning Sciences (ICLS) 2020, Volume 1 (pp. 581-584). Nashville, Tennessee: International Society of the Learning Sciences. https://repository.isls.org//handle/1/6700

**Papendieck, A.**, Ellins, K., & Clarke, J. (2020). Developing a Disciplinarily Diverse Course-based Research Experience: Outcomes and Design Considerations. In Gresalfi, M. and Horn, I. S. (Eds.), The Interdisciplinarity of the Learning Sciences, 14th International Conference of the Learning Sciences (ICLS) 2020, Volume 3 (pp. 1777-1778). Nashville, Tennessee: International Society of the Learning Sciences. https://repository.isls.org//handle/1/6438

**Papendieck, A.** (2019). More-than-Social Innovation: Techno-Axiological Enactments of an EdTech Network. American Education Research Association (AERA) Conference (Apr 4-9, 2019), Toronto.

**Papendieck, A.**, Cheah, Y. H., Eliason, C., & Clarke, J. (2018). Mapping Research and Writing Mentorship Assemblages in a Mixed Cohort Course-based Research Experience. In Kay, J. and Luckin, R. (Eds.) Rethinking Learning in the Digital Age: Making the Learning Sciences Count, 13th International Conference of the Learning Sciences (ICLS) 2018, Volume 3. London, UK: International Society of the Learning Sciences. https://repository.isls.org//handle/1/623

**Papendieck, A.**, Hughes, J. (2018). Modes of Innovation: How and Why Teachers and Entrepreneurs Use Technology for Change in Schools. American Education Research Association (AERA) Conference (Apr 13-17, 2018), New York, NY.

**Papendieck, A.**, Hughes, J. (2017). Examining the activity of teachers and technology entrepreneurs: Implications for teacher preparation. International Society for Educational Technology (ISTE) Conference (Jun 25-28, 2017), San Antonio, TX.

**Papendieck, A.**, Ngenzi, J. L., Cotton, P., Mock, N., Ndimurukuno, M. (2017). Using technology and digital resources to enhance teaching, learning, and scholarly practices in health sciences higher education: lessons learned in Rwanda. Society for Information Technology and Teacher Education (SITE) Conference (Mar 5-9, 2017), Austin, TX. https://www.learntechlib.org/p/177552/

Mock, N., Bikaako, W., **Papendieck, A.**, & Bazeyo, W. (2016). Regional research capacity development: a novel approach. American Evaluation Association (AEA) Evaluation (Oct 24-29, 2016), Atlanta, GA.

**Papendieck, A.**, Mock, N., & Kyamanywa, P. (2016). Grassroots and Global: A Blended Approach to University Faculty Development in Rwanda. International Society for Educational Technology (ISTE) Conference (Jun 26-29, 2016), Denver, CO. https://dx.doi.org/10.6084/m9.figshare.3491069.v1

**Papendieck, A**., Mock, N., & Kyamanywa, P. (2015). Tablets for Medical Education (T4ME) Project in Rwanda: Usage Patterns and Learning Outcomes Over Three Years. Distance Teaching and Learning Conference (Aug 11-13, 2015), Madison, WI. http://dx.doi.org/10.6084/m9.figshare.1591148

### Editorial Products

**Papendieck, A.**, Editor. (2018). Special Issue on Technology for Equity and Justice. Texas Education Review, 6(1).  https://review.education.utexas.edu/volume-6-issue-1